
#user  nobody;
user davuser users;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    include conf.d/*.conf;


    server {
        listen 80;
        charset utf-8; 
        server_name localhost;

        auth_basic "WebDAV";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location /link-api/ {
            proxy_pass http://127.0.0.1:8080/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            alias /var/www/data/;
            disable_symlinks off;
            
            autoindex on;
            charset utf-8;

            gzip off;
            # --- Fancyindex 配置 ---
            # fancyindex on;
            # fancyindex_exact_size off;
            # fancyindex_localtime on;
            # # 核心配置：将脚本注入到页面底部
            # fancyindex_footer "/fancyindex/footer.html";
            # --- WebDAV 配置 ---
            dav_methods PUT DELETE MKCOL COPY MOVE;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;
        }

        location /api/ {
        alias /var/www/data/;
        disable_symlinks off;
        
        autoindex on;
        autoindex_format json;
        autoindex_localtime on;  
        charset utf-8;
        gzip off;
        
        # 允许跨域（如果前端需要）
        add_header Access-Control-Allow-Origin *;
        add_header Content-Type "application/json; charset=utf-8";
    }
     
    }


}
